---
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
        environment:
          IMAGE_NAME: marcelo_delnegro/sample
    working_directory: ~/repo
    steps:
      - checkout   
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt            
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and Push Docker Image
          command: |
            docker login quay.io -u $QUAY_USERNAME -p $QUAY_PASSWORD
            docker build -t quay.io/$IMAGE_NAME:$CIRCLE_BUILD_NUM .            
            docker push quay.io/$IMAGE_NAME:$CIRCLE_BUILD_NUM
  deploy_development:
    docker:
      - image: quay.io/marcelo_delnegro/ts-docker-deployment-dev
        auth:
          username: $QUAY_USERNAME
          password: $QUAY_PASSWORD
    steps:
      - checkout   
      - run:
          name: Deploying to Development Environment
          command: |
            kubectl get pods --all-namespaces          
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy_development:
          requires:
            - build